### ISSUE TITLE
Suggestion: add create time to credentials UI

### ISSUE THREAD

**Issue by lann** [JAFLabs/wa.dev-issues#5]
For me, knowing when a credential was created is almost as useful as naming it for remembering what it was for.

**Comment by calvinrp** [comment]
Agreed. We will add shortly.

**Comment by calvinrp** [comment]
Added `Created` time and `Age`. But need to improve the timezone displayed for the `Created`. If rendered server-side is UTC and client-side is user's local time zone. Probably want both to be local time zone.

**Comment by lann** [comment]
I really like the pattern of showing a relative time and adding the local timestamp as a popover with js
